---
title: "Week-1 DV 19BCE1759"
author: "S Sabhari Girish"
date: "24/01/2022"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import the hsb2 dataset
```{r echo=TRUE}
library(lattice)
data<-mtcars
data
```

### 1. Bar plot
```{r echo=TRUE}
# Barplot of two variables
barchart(data$gear~data$wt,  data = data,
         main = "Barplot",
         col = c("chocolate", "red", "orange", "blue"))

# Barplot of two variables horizontal
barchart(data$gear~data$wt,  data = data,
         main = "Barplot",
         col = c("chocolate", "red", "orange", "blue"),
         horiz=FALSE)

# Barplot of multivariate horizontal
barchart(data$gear~data$wt|data$hp,  data = data,
         main = "Barplot",
         col = c("chocolate", "red", "orange", "blue"),
         horiz=FALSE)
```


### 2. Boxplot
```{r echo=TRUE}
# Boxplot
bwplot(data$gear ~ data$wt | data$hp,
       xlab = "gear")

# boxplots for each combination of two factors
bwplot(data$gear ~ data$wt | data$hp)

#Boxplot associated with multiple variables and alternate layout
bwplot(data$gear ~ data$wt | data$hp,
       layout = c(1, 3))

```

### 3. Cloud 3D plot
```{r echo=TRUE}
# 3d plot
cloud(data$wt~data$hp*data$mpg,main = "3D scatterplot")

# 3d scatterplot by factor level
cloud(data$wt~data$hp*data$mpg|data$disp,
      main="3D Scatterplot by gear")
```

### 4. Kernel density plot
```{r echo=TRUE}
# kernel density plot
densityplot(~data$wt)

# kernel density plots by factor level
densityplot(~data$wt|data$gear)

# kernel density plots by factor level (alternate layout)
densityplot(~data$wt|data$hp,
            layout=c(1,3))

#Kernel Density Plot together for all factors without points
densityplot(~data$wt,
            groups = data$gear,
            plot.points = FALSE)
```

### 5. Dot plot
```{r echo=TRUE}
# dotplot for each combination of two factors
dotplot(data$gear~data$wt|data$hp)

```

### 6. Histogram
```{r echo=TRUE}
# Histogram for single variable
histogram(~data$wt,data=data)

# Histogram for single variable colour
histogram(~data$hp,data=data,
          col = c("chocolate2", "seagreen"))

# Histogram for multivariate and colour
histogram(~data$wt | data$gear,data=data,
          col = c("chocolate2", "seagreen"))
```

### 7. 3D Levelplot
```{r echo=TRUE}
# levelplot
levelplot(data$wt~data$hp*data$disp,
          cuts = 50,  sub="with log scales",
          colorkey = FALSE)

# 3D Levelplot multivariate
levelplot(data$wt~data$hp*data$disp|data$gear,
          cuts = 50, 
          colorkey = FALSE)
```

### 8. Parallel plot
```{r echo=TRUE}
# Parallel plot of the values in the dataset
parallelplot(data[c(1,2,3,4,5,6)],xlab="cars",main="Parallel plot")
```

### 9. Scatterplot matrix
```{r echo=TRUE}
splom(data[c(7,8,9,10)],
      main="hsb2")
bwplot(data$gear ~ data$hp | data$wt,
       data = data,
       panel = panel.violin)
```

### 10. Strip plot
```{r echo=TRUE}
# Strip plot for the dataframe
stripplot(data$hp ~ data$wt, data = data, aspect = 1,
          jitter = T)

# Strip plot for multivariate
stripplot(data$hp~ data$wt|data$gear, data = data, aspect = 1,
          jitter = T)
```

### 11. Scatter plot
```{r echo=TRUE}
# Regular scatterplot
xyplot(data$hp~data$wt)

# Scatterplots by gear and ses
xyplot(data$hp~data$wt | data$gear)

# Scatterplot and regression line
xyplot(data$hp~data$wt,
       data = data,
       type = c("p", "r"))
```

### 12. Wireplot
```{r echo=TRUE}
wireframe(data$hp~data$wt*data$disp,
          data,colorkey=TRUE,drape=TRUE,
          scales=list(arrows=FALSE), zlim=c(0,100))
```